BS3/RubyOnRails/seed/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'miscellaneous#blank_page'
  # Miscellaneous
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

BS3/RubyOnRails/seed/app/models/application_record.rb
# :nodoc:
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BS3/RubyOnRails/seed/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def remember_me
    (super == nil) ? '1' : super
    end
end

BS3/RubyOnRails/seed/app/controllers/ajax_controller.rb
# AJAX helpers
class AjaxController < ApplicationController
  layout false

  def email_list
  end

  def email_compose
  end

  def email_opened
  end

  def email_reply
  end

  def demo_widget
  end

  def data_list
  end

  def notify_mail
  end

  def notify_notifications
  end

  def notify_tasks
  end
end

BS3/RubyOnRails/seed/app/controllers/application_controller.rb
# :nodoc:
class ApplicationController < ActionController::Base
  before_filter :set_gettext_locale
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

BS3/RubyOnRails/seed/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def set_locale
    session[:locale] = params[:locale]
    redirect_to :back
  end
end

BS3/RubyOnRails/seed/app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:register, :forgot_password]

  def login
    @simulate_no_user = true
  end

  def register
    @simulate_no_user = true
  end

  def forgot_password
    @simulate_no_user = true
  end

  def locked_screen
    @simulate_no_user = true
    @lock_screen = true
  end

  def blank_page
  end
end

BS3/RubyOnRails/seed/app/helpers/application_helper.rb
# :nodoc:
module ApplicationHelper
  def left_menu
    left_menu_entries(left_menu_content)
  end

  private

  def selected_locale
    locale = FastGettext.locale
    locale_list.detect {|entry| entry[:locale] == locale}
  end

  def locale_list
    [
      {
        flag: 'us',
        locale: 'en',
        name: 'English (US)',
        alt_name: 'United States'
      },
      {
        flag: 'fr',
        locale: 'fr',
        name: 'Français',
        alt_name: 'France'
      },
      {
        flag: 'es',
        locale: 'es',
        name: 'Español',
        alt_name: 'Spanish'
      },
      {
        flag: 'de',
        locale: 'de',
        name: 'Deutsch',
        alt_name: 'German'
      },
      {
        flag: 'jp',
        locale: 'ja',
        name: '日本語',
        alt_name: 'Japan'
      },
      {
        flag: 'cn',
        locale: 'zh',
        name: '中文',
        alt_name: 'China'
      },
      {
        flag: 'it',
        locale: 'it',
        name: 'Italiano',
        alt_name: 'Italy'
      },
      {
        flag: 'pt',
        locale: 'pt',
        name: 'Portugal',
        alt_name: 'Portugal'
      },
      {
        flag: 'ru',
        locale: 'ru',
        name: 'Русский язык',
        alt_name: 'Russia'
      },
      {
        flag: 'kr',
        locale: 'kr',
        name: '한국어',
        alt_name: 'Korea'
      },
    ]
  end

  def left_menu_entries(entries = [])
    output = ''
    entries.each do |entry|
      children_selected = entry[:children] &&
        entry[:children].any? {|child| current_page?(child[:href]) }
      entry_selected =  current_page?(entry[:href])
      li_class =
      case
        when children_selected
          'open'
        when entry_selected
          'active'
      end
      output +=
        content_tag(:li, class: li_class) do
          subentry = ''
          subentry +=
            link_to entry[:href], title: entry[:title], class: entry[:class], target: entry[:target] do
              link_text = ''
              link_text += entry[:content].html_safe
              if entry[:children]
                if children_selected
                  link_text += '<b class="collapse-sign"><em class="fa fa-minus-square-o"></em></b>'
                else
                  link_text += '<b class="collapse-sign"><em class="fa fa-plus-square-o"></em></b>'
                end
              end

              link_text.html_safe
            end
          if entry[:children]
            if children_selected
              ul_style = 'display: block'
            else
              ul_style = ''
            end
            subentry +=
              "<ul style='#{ul_style}'>" +
                left_menu_entries(entry[:children]) +
                "</ul>"
          end

          subentry.html_safe
        end
    end
    output.html_safe
  end

  def left_menu_content
    [
      {
        href: root_path,
        title: _('blank'),
        content: "<i class='fa fa-lg fa-fw fa-home'></i> <span class='menu-item-parent'>" + _('Blank') + "</span>",
      },
    ]
  end

end

BS3/RubyOnRails/seed/app/views/layouts/_footer.html.erb
<div class="page-footer">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <span class="txt-color-white">SmartAdmin 1.8.x <span class="hidden-xs"> - Web Application Framework</span> © 2014-2015</span>
    </div>

  </div>
</div>

BS3/RubyOnRails/seed/app/views/layouts/_header.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo"> <%= image_tag 'logo.png', alt: 'SmartAdmin' %> </span>
    <!-- END LOGO PLACEHOLDER -->

    <% if current_user && !@simulate_no_user %>
      <!-- Note: The activity badge color changes when clicked and resets the number to 0
      Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
      <span id="activity" class="activity-dropdown"> <i class="fa fa-user"></i> <b class="badge"> 21 </b> </span>

      <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
      <div class="ajax-dropdown">

        <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_mail_path %>">
            <%= _('Msgs') %> (14) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_notifications_path %>">
            <%= _('notify') %> (3) </label>
          <label class="btn btn-default">
            <input type="radio" name="activity" id="<%= ajax_notify_tasks_path %>">
            <%= _('Tasks') %> (4) </label>
        </div>

        <!-- notification content -->
        <div class="ajax-notifications custom-scroll">

          <div class="alert alert-transparent">
            <h4>Click a button to show messages here</h4>
            This blank page message helps protect your privacy, or you can show the first message here automatically.
          </div>

          <i class="fa fa-lock fa-4x fa-border"></i>

        </div>
        <!-- end notification content -->

        <!-- footer: refresh area -->
            <span> Last updated on: 12/12/2013 9:43AM
              <button type="button" data-loading-text="<i class='fa fa-refresh fa-spin'></i> Loading..." class="btn btn-xs btn-default pull-right">
                <i class="fa fa-refresh"></i>
              </button>
            </span>
        <!-- end footer -->

      </div>
      <!-- END AJAX-DROPDOWN -->
    <% end %>
  </div>
  <%= yield :top_right %>

  <% if current_user && !@simulate_no_user %>
    <!-- projects dropdown -->
    <div class="project-context hidden-xs">

      <span class="label">Projects:</span>
      <span class="project-selector dropdown-toggle" data-toggle="dropdown"><%= _('Recent projects') %> <i class="fa fa-angle-down"></i></span>

      <!-- Suggestion: populate this list with fetch and push technique -->
      <ul class="dropdown-menu">
        <li>
          <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
        </li>
        <li>
          <a href="javascript:void(0);">Notes on pipeline upgradee</a>
        </li>
        <li>
          <a href="javascript:void(0);">Assesment Report for merchant account</a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
        </li>
      </ul>
      <!-- end dropdown-menu-->

    </div>
    <!-- end projects dropdown -->

    <!-- pulled right: nav area -->
    <div class="pull-right">

      <!-- collapse menu button -->
      <div id="hide-menu" class="btn-header pull-right">
        <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
      </div>
      <!-- end collapse menu -->

      <!-- #MOBILE -->
      <!-- Top menu profile link : this shows only when top menu is active -->
      <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
        <li class="">
          <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <%= image_tag 'avatars/sunny.png', alt: 'John Doe', class: 'online' %>
          </a>
          <ul class="dropdown-menu pull-right">
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
            </li>
          </ul>
        </li>
      </ul>

      <!-- logout button -->
      <div id="logout" class="btn-header transparent pull-right">
        <span>
          <%= link_to(destroy_user_session_path, title: 'Sign Out', data: {action: 'userLogout', 'logout-msg' => 'You can improve your security further after logging out by closing this opened browser'}) do %>
            <i class="fa fa-sign-out"></i>
          <% end %>
        </span>
      </div>
      <!-- end logout button -->

      <!-- search mobile button (this is hidden till mobile view port) -->
      <div id="search-mobile" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
      </div>
      <!-- end search mobile button -->

      <!-- input: search field -->
      <form action="<%= root_path %>" class="header-search pull-right">
        <input id="search-fld"  type="text" name="param" placeholder="<%= _('Find reports and more') %>" data-autocomplete='[
            "ActionScript",
            "AppleScript",
            "Asp",
            "BASIC",
            "C",
            "C++",
            "Clojure",
            "COBOL",
            "ColdFusion",
            "Erlang",
            "Fortran",
            "Groovy",
            "Haskell",
            "Java",
            "JavaScript",
            "Lisp",
            "Perl",
            "PHP",
            "Python",
            "Ruby",
            "Scala",
            "Scheme"]'>
        <button type="submit">
          <i class="fa fa-search"></i>
        </button>
        <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
      </form>
      <!-- end input: search field -->

      <!-- fullscreen button -->
      <div id="fullscreen" class="btn-header transparent pull-right">
        <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
      </div>
      <!-- end fullscreen button -->

      <!-- multiple lang dropdown : find all flags in the flags page -->
      <%= render 'layouts/locale_select' %>
      <!-- end multiple lang -->

    </div>
    <!-- end pulled right: nav area -->
  <% end %>

</header>

BS3/RubyOnRails/seed/app/views/layouts/_left_panel.html.erb
<aside id="left-panel">

  <!-- User info -->
  <div class="login-info">
				<span> <!-- User image size is adjusted inside CSS, it should stay as it -->

					<a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <%= image_tag 'avatars/sunny.png', alt: 'me', class: 'online' %>
            <span>
							john.doe
						</span>
            <i class="fa fa-angle-down"></i>
          </a>

				</span>
  </div>
  <!-- end user info -->

  <!-- NAVIGATION : This navigation is also responsive-->
  <nav>
    <!--
    NOTE: Notice the gaps after each icon usage <i></i>..
    Please note that these links work a bit different than
    traditional href="" links. See documentation for details.
    -->

    <ul>
      <%= left_menu %>
    </ul>
  </nav>


			<span class="minifyme" data-action="minifyMenu">
				<i class="fa fa-arrow-circle-left hit"></i>
			</span>

</aside>

BS3/RubyOnRails/seed/app/views/layouts/_locale_select.html.erb
<% @selected_locale = selected_locale %>
<ul class="header-dropdown-list hidden-xs">
  <li>
    <%= link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do %>
      <%= image_tag "blank.gif", class: "flag flag-#{@selected_locale[:flag]}", alt: @selected_locale[:alt_name] %> <span> <%= @selected_locale[:name] %> </span> <i class="fa fa-angle-down"></i>
  <% end %>
    <ul class="dropdown-menu pull-right">
      <% locale_list.each do |locale| %>
        <li class="<%= 'active' if locale[:locale] == @selected_locale[:locale] %>">
          <%= link_to home_set_locale_path(locale: locale[:locale]) do %>
            <%= image_tag "blank.gif", class: "flag flag-#{locale[:flag]}", alt: locale[:alt_name] %> <%= locale[:name] %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>

BS3/RubyOnRails/seed/app/views/layouts/_scripts.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    pageSetUp();
  })
</script>

BS3/RubyOnRails/seed/app/views/layouts/_tiles.html.erb
<div id="shortcut">
  <ul>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blue' do %>
        <span class="iconbox"> <i class="fa fa-envelope fa-4x"></i> <span>Mail <span class="label pull-right bg-color-darken">14</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-orangeDark' do %>
        <span class="iconbox"> <i class="fa fa-calendar fa-4x"></i> <span>Calendar</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-purple' do %>
        <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-blueDark' do %>
        <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes bg-color-greenLight' do %>
        <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span>
      <% end %>
    </li>
    <li>
      <%= link_to root_path, class: 'jarvismetro-tile big-cubes selected bg-color-pinkDark' do %>
        <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span>
      <% end %>
    </li>
  </ul>
</div>

BS3/RubyOnRails/seed/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us" id="<%= yield :html_id %>">
<head>
  <meta charset="utf-8">

  <title> SmartAdmin - Ruby on Rails </title>
  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <%= stylesheet_link_tag 'application', media: 'screen' %>

  <!-- FAVICONS -->
  <%= favicon_link_tag 'favicon/favicon.ico' %>
  <%= favicon_link_tag 'favicon/favicon.ico', rel: 'icon' %>

  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700' %>

  <!-- Specifying a Webpage Icon for Web Clip
     Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
  <%= favicon_link_tag 'splash/sptouch-icon-iphone.png', type: 'image/png', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-ipad.png', type: 'image/png', sizes: '76x76', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-iphone-retina.png', type: 'image/png', sizes: '120x120', rel: 'apple-touch-icon' %>
  <%= favicon_link_tag 'splash/touch-icon-ipad-retina.png', type: 'image/png', sizes: '152x152', rel: 'apple-touch-icon' %>

  <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <!-- Startup image for web apps -->
  <%= favicon_link_tag 'splash/ipad-landscape.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)' %>
  <%= favicon_link_tag 'splash/ipad-portrait.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)' %>
  <%= favicon_link_tag 'splash/iphone.png', type: 'image/png', rel: 'apple-touch-startup-image', media: 'screen and (max-device-width: 320px)' %>

  <%= yield :head %>
</head>

<!--

TABLE OF CONTENTS.

Use search to find needed section.

===================================================================

|  01. #CSS Links                |  all CSS links and file paths  |
|  02. #FAVICONS                 |  Favicon links and file paths  |
|  03. #GOOGLE FONT              |  Google font link              |
|  04. #APP SCREEN / ICONS       |  app icons, screen backdrops   |
|  05. #BODY                     |  body tag                      |
|  06. #HEADER                   |  header tag                    |
|  07. #PROJECTS                 |  project lists                 |
|  08. #TOGGLE LAYOUT BUTTONS    |  layout buttons and actions    |
|  09. #MOBILE                   |  mobile view dropdown          |
|  10. #SEARCH                   |  search field                  |
|  11. #NAVIGATION               |  left panel & navigation       |
|  12. #RIGHT PANEL              |  right panel userlist          |
|  13. #MAIN PANEL               |  main panel                    |
|  14. #MAIN CONTENT             |  content holder                |
|  15. #PAGE FOOTER              |  page footer                   |
|  16. #SHORTCUT AREA            |  dropdown shortcuts area       |
|  17. #PLUGINS                  |  all scripts and plugins       |

===================================================================

-->

<!-- #BODY -->
<!-- Possible Classes

  * 'smart-style-{SKIN#}'
  * 'smart-rtl'         - Switch theme mode to RTL
  * 'menu-on-top'       - Switch to top navigation (no DOM change required)
  * 'no-menu'			  - Hides the menu completely
  * 'hidden-menu'       - Hides the main menu but still accessable by hovering over left edge
  * 'fixed-header'      - Fixes the header
  * 'fixed-navigation'  - Fixes the main menu
  * 'fixed-ribbon'      - Fixes breadcrumb
  * 'fixed-page-footer' - Fixes footer
  * 'container'         - boxed layout mode (non-responsive: will not work with fixed-navigation & fixed-ribbon)
-->
<body class="<%= yield :body_class %>">

<!-- HEADER -->
<%= render partial: 'layouts/header' unless @lock_screen %>
<!-- END HEADER -->

<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<%= render partial: 'layouts/left_panel' if current_user && !@simulate_no_user %>
<!-- END NAVIGATION -->

<!-- MAIN PANEL -->
<div id="main" role="main">
  <%= yield :ribbon %>
  <% if notice %>
    <div class="alert alert-success fade in">
      <button data-dismiss="alert" class="close">
        ×
      </button>
      <i class="fa-fw fa fa-check"></i>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning fade in">
      <button data-dismiss="alert" class="close">
        ×
      </button>
      <i class="fa-fw fa fa-warning"></i>
      <%= alert %>
    </div>
  <% end %>
  <%= yield %>
</div>
<!-- END MAIN PANEL -->

<!-- PAGE FOOTER -->
<%= render partial: 'layouts/footer' if current_user && !@simulate_no_user %>
<!-- END PAGE FOOTER -->

<!-- SHORTCUT AREA : With large tiles (activated via clicking user name tag)
Note: These tiles are completely responsive,
you can add as many as you like
-->
<%= render partial: 'layouts/tiles' if current_user && !@simulate_no_user %>
<!-- END SHORTCUT AREA -->

<!--================================================== -->

<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<%= javascript_include_tag 'plugin/pace/pace', 'data-pace-options' => '{ "restartOnRequestAfter": true }' %>

<%= javascript_include_tag 'application' %>


<!--[if IE 8]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->

<%= yield(:scripts).present? ? yield(:scripts) : render(partial: 'layouts/scripts') %>

<!-- Your GOOGLE ANALYTICS CODE Below -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXXXXX-X']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>

</html>